# Используем базовый xrender, чтобы не лагало железо
backend = "xrender";
vsync = true;

# Включаем чтение прозрачности приложений (для kitty)
detect-client-opacity = true;
inactive-opacity = 0.92;
active-opacity = 1.0;

# Настройка теней
shadow = true;
shadow-radius = 8;
shadow-offset-x = -8;
shadow-offset-y = -8;
shadow-opacity = 0.35;
shadow-color = "#BC71FF";

# Принудительное скругление углов ТОЛЬКО для Polybar
corner-radius = 12;
rounded-corners-exclude = [
  "window_type = 'desktop'",
  "class_g != 'Polybar'"
];
