# --- Шрифты ---
font_family      monospace
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

# --- Прозрачность (за счёт picom будет размытие) ---
background_opacity         0.85
dynamic_background_opacity yes

# --- Настройки окна ---
window_padding_width 8
remember_window_size  no
initial_window_width  800
initial_window_height 500

# --- Цветовая схема (Cyberpunk / Vaporwave) ---
background            #111216
foreground            #F7E3EC
cursor                #FF5E97
cursor_text_color     #111216

# Цвета для вывода в терминале (сделаем их ярче и неоновее)
# Черный / Серый
color0 #1A1B26
color8 #4C4B63

# Красный (Розовый аниме-румянец)
color1 #FF5E97
color9 #FF7EA5

# Зеленый (Мятный неоновый)
color2 #00F5D4
color10 #70F7FF

# Желтый / Оранжевый
color3 #FFE66D
color11 #FFF3B0

# Синий / Фиолетовый (Основной неон)
color4 #BC71FF
color12 #D6A3FF

# Пурпурный
color5 #9B5DE5
color13 #F15BB5

# Циановый
#color6 #00BBF9
#color14 #00F5D4

# Белый
color7 #F7E3EC
color15 #FFFFFF

# Перекрашиваем капризный бирюзовый цвет в наш фиолетовый неон
color6  #BC71FF
color14 #BC71FF
